Output execution results after ESLint execution; set the default atrifact's life time; add the comment to the PR's conversation

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -169,16 +169,76 @@ jobs:
         run: |
           npm clean-install --include dev
           npm run lint:ci || true
+          echo "--------------------------"
+          echo "ESLint execution results :"
+          echo "--------------------------"
+          cat ./eslint-report.txt || echo "ESLint report file not found."
 
       - name: ESLint artifact
+        id: eslint-artifact
         uses: actions/upload-artifact@v4
         with:
           name: ESLint-report
           path: ./ui/eslint-report.txt
           if-no-files-found: warn
-          retention-days: 1
           compression-level: 9
           overwrite: true
+
+      - name: Publish ESlint report in PR comment
+        uses: actions/github-script@v7
+        if: github.event_name == 'pull_request'
+        with:
+          github-token: ${{ secrets.COMMENT_TOKEN }}
+          script: |
+            let ESLintResults = ${{ steps.eslint-artifact.outputs.artifact-url }};
+            let output = '';
+
+            const comments = await github.rest.issues.listComments({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo
+            });
+
+            const botComment = comments.data.find(
+              comment => comment.user.login === 'github-actions[bot]'
+              && comment.body.includes('ESLint')
+            );
+
+            if (ESLintResults) {
+
+              output += '#### ESLint issues:\n';
+              output += 'ESLint detected issues during execution.\n';
+              output += '\n[ESLint execution report](' + ESLintResults + ')\n';
+              output += '\nMake sure that you're logged in to be able to access the report.';
+              output += '\nThe report is accessible within 90 days after the last UI testing workflow execution time.';
+              output += '\nAfter that time you need to go to the ESLint execution step in the Actions tab to see the same results.';
+
+              if (botComment) {
+                await github.rest.issues.updateComment({
+                  comment_id: botComment.id,
+                  owner: context.repo.owner,
+                  repo: context.repo.repo,
+                  body: output
+                });
+              } else {
+                await github.rest.issues.createComment({
+                  issue_number: context.issue.number,
+                  owner: context.repo.owner,
+                  repo: context.repo.repo,
+                  body: output
+                });
+              }
+
+            } else {
+
+              if (botComment) {
+                await github.rest.issues.deleteComment({
+                  comment_id: botComment.id,
+                  owner: context.repo.owner,
+                  repo: context.repo.repo
+                });
+              }
+            }
 
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
